-- Enable Storage
insert into storage.buckets (id, name, public)
values ('properties', 'properties', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false) -- Private bucket for sensitive docs
on conflict (id) do nothing;

-- Policies for Properties Bucket (Public Read, Authenticated Upload)
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'properties' );

create policy "Authenticated Users can upload property images"
  on storage.objects for insert
  with check ( bucket_id = 'properties' and auth.role() = 'authenticated' );

create policy "Users can update their own property images"
  on storage.objects for update
  using ( bucket_id = 'properties' and auth.uid() = owner );

create policy "Users can delete their own property images"
  on storage.objects for delete
  using ( bucket_id = 'properties' and auth.uid() = owner );

-- Policies for Documents Bucket (Private, Owner Access Only)
create policy "Users can upload their own documents"
  on storage.objects for insert
  with check ( bucket_id = 'documents' and auth.uid() = owner );

create policy "Users can view their own documents"
  on storage.objects for select
  using ( bucket_id = 'documents' and auth.uid() = owner );

-- Allow landlords to view documents linked to applications for their properties
-- (This is complex in RLS for storage, often handled by signed URLs in app logic. 
-- For MVP, we'll rely on signed URLs generated by the backend/client for specific access)
